### PR TITLE
Search fix

### PR DESCRIPTION
**Pull request by fleur0121**
Search functions are completed & fixed bugs in PR#73.
What's new:

- If the recipe is not found, let the users know that the recipe is not found
- Made search bar text bolder
- Navigate users to the recipe page if they click "check it out" in the home page recipe card
- Changed some buttons to the ModifiedButton component
- Added some test setups (with Vitest & React test library)

To run the app with this branch, you may need to install

```
npm install -D vitest
npm install jsdom --save-dev
npm install @testing-library/react @testing-library/jest-dom --save-dev  
```

- [ ] I made many changes to packages & configs, so please see if this branch also works on your side.

I think the Spoonacular API features we need to work on for the marks are almost done!

### CODE REVIEW

**Review by mgao08 — COMMENTED** [review]
The search bar in `/testSearch/` page does not work, I think it worked before this fix right? If that search bar is not meant to work for now then just ignore this comment.

The error message I got:
截屏2024-03-13 13 05 13

**Comment by fleur0121** [comment]
> The search bar in `/testSearch/` page does not work, I think it worked before this fix right? If that search bar is not meant to work for now then just ignore this comment.
> 
> The error message I got: 截屏2024-03-13 13 05 13

Thank you for letting me know! I made a new commit, and it should works.

**Review by mgao08 — APPROVED** [review]
The search bar is now back online, and I feel like it will be better the searching through advanced search panel can also refresh the search result as how we use the search bar.

**Comment by fleur0121** [comment]
> The search bar is now back online, and I feel like it will be better the searching through advanced search panel can also refresh the search result as how we use the search bar.

That's true, I'll make a issue to fix it

**Pull request merged**
