### PR TITLE
Search

### PR DESCRIPTION
**Pull request by fleur0121**
Search functions are completed.
What's new:
- If the recipe is not found, let the users know that the recipe is not found
- make search bar text bolder
- Navigate users to the recipe page if they click "check it out" in the home page recipe card
- change some buttons to ModifiedButton component

I think the Spoonacular API features we need to work on for the marks are almost done!

### CODE REVIEW

**Comment by fleur0121** [comment]
Fix conflicts real quick

**Comment by fleur0121** [comment]
> Fix conflicts in real quick

Fixed

**Review by mgao08 — COMMENTED** [review]
I got this when trying to run the updated flexy-cook-api, I guess I need to install something extra. Could you please provide us some install instruction for the new model added in this update?

截屏2024-03-13 10 46 20

**Comment by fleur0121** [comment]
> I got this when trying to run the updated flexy-cook-api, I guess I need to install something extra. Could you please provide us some install instruction for the new model added in this update?
> 
> 截屏2024-03-13 10 46 20

I checked it, and it seems like Yuna's update. I'm gonna ask her about this

**Comment by fleur0121** [comment]
i need to fix something

**Pull request closed without merging**
