### PR TITLE
Alignment fix of navbar and footer

### PR DESCRIPTION
**Pull request by mgao08**
Changes made:

- Adjusted structure of navbar & footer for them to be better aligned with the body section.
- The navbar & footer are more responsive to different screen size.
- Modified CSS files for navbar to use CSS variables as color settings.

**No need to go through the codes, just pull and see the layout when reviewing.** 

_NOTE: the footer might not look strictly aligned with the body. Footer items are buttons and when hovering on the buttons you can see the buttons are aligned._

### CODE REVIEW

**Comment by mgao08** [comment]
Also please help me test the `max-width: 1200px` on navbar, footer and home page body contents. My device screen size is not large enough to test it ^ ^

**Review by fleur0121 — COMMENTED** [review]
There are some conflicts, so please remove the main one. Thank you for organizing my messy code

**Comment by fleur0121** [comment]
> There are some conflicts, so please remove the main one. Thank you for organizing my messy code

**Comment by mgao08** [comment]
> Screenshot 2024-03-10 at 10 51 49 PM Is this right?

Nope lol... Which resolution are you on? xxl screen size?

**Comment by fleur0121** [comment]
> > Screenshot 2024-03-10 at 10 51 49 PM Is this right?
> 
> Nope lol... Which resolution are you on? xxl screen size?

Maybe...? My screen size is about 1670 * 600

**Review by fleur0121 — APPROVED** [review]

**Pull request merged**
